name: Build & Deploy
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Build multi platform
              uses: dawidd6/action-docker-publish-changed@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  token: ${{secrets.GITHUB_TOKEN}}
                  platforms: linux/amd64,linux/arm64,linux/arm/v7
                  tag: latest
            - name: Deploy
              uses: wei/curl@v1
              with:
                  args: -H "X-Docker-Token:${{ secrets.WEBHOOK_AUTH_TOKEN }}"  -X GET "${{ secrets.WEBHOOK_URL }}?DOCKER_SERVICE_NAME=automation_${{ secrets.PROJECT_NAME }}&DOCKER_IMAGE_PREFIX=${{ secrets.DOCKER_USERNAME }}&DOCKER_IMAGE_NAME=${{ secrets.PROJECT_NAME }}&DOCKER_IMAGE_TAG=${{ secrets.DOCKER_IMAGE_TAG }}"
